{"expireTime":9007200882776296000,"key":"gatsby-plugin-mdx-entire-payload-0487024629d60722720994ef998b1a11-/funycode-undefined","val":{"mdast":{"type":"root","children":[{"type":"heading","depth":2,"children":[{"type":"text","value":"Throw, Throws and Throwable in Java","position":{"start":{"line":1,"column":4,"offset":3},"end":{"line":1,"column":39,"offset":38},"indent":[]}}],"position":{"start":{"line":1,"column":1,"offset":0},"end":{"line":1,"column":39,"offset":38},"indent":[]}},{"type":"paragraph","children":[{"type":"text","value":"The “throw” keyword is used to throw an exception. We can define our own set of conditions or rules and throw an exception explicitly using throw keyword. It is possible for your program to throw an exception explicitly, using the throw statement. The general form of throw is shown here:","position":{"start":{"line":2,"column":1,"offset":40},"end":{"line":2,"column":289,"offset":328},"indent":[]}}],"position":{"start":{"line":2,"column":1,"offset":40},"end":{"line":2,"column":289,"offset":328},"indent":[]}},{"type":"heading","depth":2,"children":[{"type":"text","value":"throw Throwableinstance;","position":{"start":{"line":3,"column":4,"offset":333},"end":{"line":3,"column":28,"offset":357},"indent":[]}}],"position":{"start":{"line":3,"column":1,"offset":330},"end":{"line":3,"column":28,"offset":357},"indent":[]}},{"type":"list","ordered":false,"start":null,"spread":false,"children":[{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"Throwableinstance must be an object of type Throwable or a subclass of Throwable.","position":{"start":{"line":4,"column":3,"offset":361},"end":{"line":4,"column":84,"offset":442},"indent":[]}}],"position":{"start":{"line":4,"column":3,"offset":361},"end":{"line":4,"column":84,"offset":442},"indent":[]}}],"position":{"start":{"line":4,"column":1,"offset":359},"end":{"line":4,"column":84,"offset":442},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"Simple types, such as int or char, as well as non-Throwable classes, such as String and Object, cannot be used as exceptions.","position":{"start":{"line":5,"column":3,"offset":446},"end":{"line":5,"column":128,"offset":571},"indent":[]}}],"position":{"start":{"line":5,"column":3,"offset":446},"end":{"line":5,"column":128,"offset":571},"indent":[]}}],"position":{"start":{"line":5,"column":1,"offset":444},"end":{"line":5,"column":128,"offset":571},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"There are two ways you can obtain a Throwable object: using a parameter into a catch clause, or creating one with the new operator.","position":{"start":{"line":6,"column":3,"offset":575},"end":{"line":6,"column":134,"offset":706},"indent":[]}}],"position":{"start":{"line":6,"column":3,"offset":575},"end":{"line":6,"column":134,"offset":706},"indent":[]}}],"position":{"start":{"line":6,"column":1,"offset":573},"end":{"line":6,"column":134,"offset":706},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"The flow of execution stops immediately after the throw statement; any subsequent statements are not executed.","position":{"start":{"line":7,"column":3,"offset":710},"end":{"line":7,"column":113,"offset":820},"indent":[]}}],"position":{"start":{"line":7,"column":3,"offset":710},"end":{"line":7,"column":113,"offset":820},"indent":[]}}],"position":{"start":{"line":7,"column":1,"offset":708},"end":{"line":7,"column":113,"offset":820},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"The nearest enclosing try block is inspected to see if it has a catch statement that matches the type of the exception.","position":{"start":{"line":8,"column":3,"offset":824},"end":{"line":8,"column":122,"offset":943},"indent":[]}}],"position":{"start":{"line":8,"column":3,"offset":824},"end":{"line":8,"column":122,"offset":943},"indent":[]}}],"position":{"start":{"line":8,"column":1,"offset":822},"end":{"line":8,"column":122,"offset":943},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"If it does find a match, control is transferred to that statement. If not, then the next enclosing try statement is inspected, and so on.","position":{"start":{"line":9,"column":3,"offset":947},"end":{"line":9,"column":140,"offset":1084},"indent":[]}}],"position":{"start":{"line":9,"column":3,"offset":947},"end":{"line":9,"column":140,"offset":1084},"indent":[]}}],"position":{"start":{"line":9,"column":1,"offset":945},"end":{"line":9,"column":140,"offset":1084},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"If no matching catch is found, then the default exception handler halts the program and prints the stack trace.","position":{"start":{"line":10,"column":3,"offset":1088},"end":{"line":10,"column":114,"offset":1199},"indent":[]}}],"position":{"start":{"line":10,"column":3,"offset":1088},"end":{"line":10,"column":114,"offset":1199},"indent":[]}}],"position":{"start":{"line":10,"column":1,"offset":1086},"end":{"line":10,"column":114,"offset":1199},"indent":[]}}],"position":{"start":{"line":4,"column":1,"offset":359},"end":{"line":10,"column":114,"offset":1199},"indent":[1,1,1,1,1,1]}},{"type":"heading","depth":3,"children":[{"type":"text","value":"Example-1: Write a java program to implement throw keyword in java.","position":{"start":{"line":11,"column":5,"offset":1205},"end":{"line":11,"column":72,"offset":1272},"indent":[]}}],"position":{"start":{"line":11,"column":1,"offset":1201},"end":{"line":11,"column":72,"offset":1272},"indent":[]}},{"type":"code","lang":"js","meta":null,"value":"//Write a java program to implement throw keyword in java.\n  public class FunyCodeException {\n    static void throwDemo()\n      {\n       try\n      {\n       throw new NullPointerException(\"demo\");\n      }\n     catch(NullPointerException e)\n     {\n        System.out.println(\"Caught inside throwDemo.\");\n        throw e; // rethrow the exception\n      }\n    }\n    public static void main(String args[])\n      {\n       try\n      {\n       throwDemo();\n      }\n      catch(NullPointerException e)\n      {\n        System. out .println (\"Recaught Exception\");\n       }\n      }\n     }","position":{"start":{"line":12,"column":1,"offset":1274},"end":{"line":39,"column":4,"offset":1887},"indent":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}},{"type":"code","lang":null,"meta":null,"value":"Output:\nCaught inside throwDemo.\nRecaught Exception","position":{"start":{"line":40,"column":1,"offset":1889},"end":{"line":44,"column":4,"offset":1952},"indent":[1,1,1,1]}},{"type":"heading","depth":3,"children":[{"type":"text","value":"Example-2: Write a java program to check weather eligible or not in voting registration using throw keyword in java.","position":{"start":{"line":45,"column":5,"offset":1958},"end":{"line":45,"column":121,"offset":2074},"indent":[]}}],"position":{"start":{"line":45,"column":1,"offset":1954},"end":{"line":45,"column":121,"offset":2074},"indent":[]}},{"type":"code","lang":"js","meta":null,"value":"//Write a java program to check weather eligible or not in voting registration using throw keyword in java.\n  public class FunyCodeException {\n    static void ageCheck(int age) {\n      if (age<18)\n        throw new ArithmeticException(\"Not Elligible for Voting\");\n      else\n        System.out.println(\"Welcome, Elligible for Voting\");\n      }\n    public static void main(String args[]) {\n       ageCheck(10);\n      }\n    }","position":{"start":{"line":46,"column":1,"offset":2076},"end":{"line":59,"column":4,"offset":2522},"indent":[1,1,1,1,1,1,1,1,1,1,1,1,1]}},{"type":"code","lang":null,"meta":null,"value":"Output:\nException in thread \"main\" java.lang.ArithmeticException: Not Elligible for Voting\nat FunyCodeException.ageCheck(FunyCodeException.java:5)\nat FunyCodeException.main(FunyCodeException.java:10)","position":{"start":{"line":60,"column":1,"offset":2524},"end":{"line":65,"column":4,"offset":2736},"indent":[1,1,1,1,1]}},{"type":"heading","depth":2,"children":[{"type":"text","value":"Throws in Java","position":{"start":{"line":66,"column":4,"offset":2741},"end":{"line":66,"column":18,"offset":2755},"indent":[]}}],"position":{"start":{"line":66,"column":1,"offset":2738},"end":{"line":66,"column":18,"offset":2755},"indent":[]}},{"type":"list","ordered":false,"start":null,"spread":false,"children":[{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"Throws keyword is used for handling checked exceptions . By using throws we can declare multiple exceptions in one go.","position":{"start":{"line":67,"column":3,"offset":2759},"end":{"line":67,"column":121,"offset":2877},"indent":[]}}],"position":{"start":{"line":67,"column":3,"offset":2759},"end":{"line":67,"column":121,"offset":2877},"indent":[]}}],"position":{"start":{"line":67,"column":1,"offset":2757},"end":{"line":67,"column":121,"offset":2877},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"If a method is capable of causing an exception that it does not handled, it must specify the behavior so that callers of the method can guard themselves against that exception.","position":{"start":{"line":68,"column":3,"offset":2881},"end":{"line":68,"column":179,"offset":3057},"indent":[]}}],"position":{"start":{"line":68,"column":3,"offset":2881},"end":{"line":68,"column":179,"offset":3057},"indent":[]}}],"position":{"start":{"line":68,"column":1,"offset":2879},"end":{"line":68,"column":179,"offset":3057},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"You do this by including a throws clause in the method’s declaration.","position":{"start":{"line":69,"column":3,"offset":3061},"end":{"line":69,"column":72,"offset":3130},"indent":[]}}],"position":{"start":{"line":69,"column":3,"offset":3061},"end":{"line":69,"column":72,"offset":3130},"indent":[]}}],"position":{"start":{"line":69,"column":1,"offset":3059},"end":{"line":69,"column":72,"offset":3130},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"A throws clause lists the types of exceptions that a method might throw.","position":{"start":{"line":70,"column":3,"offset":3134},"end":{"line":70,"column":75,"offset":3206},"indent":[]}}],"position":{"start":{"line":70,"column":3,"offset":3134},"end":{"line":70,"column":75,"offset":3206},"indent":[]}}],"position":{"start":{"line":70,"column":1,"offset":3132},"end":{"line":70,"column":75,"offset":3206},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"This is necessary for all exceptions, except those of type Error or RuntimeException, or any of their subclasses.","position":{"start":{"line":71,"column":3,"offset":3210},"end":{"line":71,"column":116,"offset":3323},"indent":[]}}],"position":{"start":{"line":71,"column":3,"offset":3210},"end":{"line":71,"column":116,"offset":3323},"indent":[]}}],"position":{"start":{"line":71,"column":1,"offset":3208},"end":{"line":71,"column":116,"offset":3323},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"All other exceptions that a method can throw must be declared in the throws clause.","position":{"start":{"line":72,"column":3,"offset":3327},"end":{"line":72,"column":86,"offset":3410},"indent":[]}}],"position":{"start":{"line":72,"column":3,"offset":3327},"end":{"line":72,"column":86,"offset":3410},"indent":[]}}],"position":{"start":{"line":72,"column":1,"offset":3325},"end":{"line":72,"column":86,"offset":3410},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"If they are not, a compile-time error will result.","position":{"start":{"line":73,"column":3,"offset":3414},"end":{"line":73,"column":53,"offset":3464},"indent":[]}}],"position":{"start":{"line":73,"column":3,"offset":3414},"end":{"line":73,"column":53,"offset":3464},"indent":[]}}],"position":{"start":{"line":73,"column":1,"offset":3412},"end":{"line":73,"column":53,"offset":3464},"indent":[]}}],"position":{"start":{"line":67,"column":1,"offset":2757},"end":{"line":73,"column":53,"offset":3464},"indent":[1,1,1,1,1,1]}},{"type":"code","lang":null,"meta":null,"value":"Syntax:\ntype method-name(parameter-list) throws exception-list\n{\n// body of method\n}","position":{"start":{"line":75,"column":1,"offset":3468},"end":{"line":81,"column":4,"offset":3566},"indent":[1,1,1,1,1,1]}},{"type":"list","ordered":false,"start":null,"spread":false,"children":[{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"Exception-list is a comma-separated list of the exceptions that a method can throw.","position":{"start":{"line":82,"column":3,"offset":3570},"end":{"line":82,"column":86,"offset":3653},"indent":[]}}],"position":{"start":{"line":82,"column":3,"offset":3570},"end":{"line":82,"column":86,"offset":3653},"indent":[]}}],"position":{"start":{"line":82,"column":1,"offset":3568},"end":{"line":82,"column":86,"offset":3653},"indent":[]}}],"position":{"start":{"line":82,"column":1,"offset":3568},"end":{"line":82,"column":86,"offset":3653},"indent":[]}},{"type":"heading","depth":3,"children":[{"type":"text","value":"Example-3: Write a java program to demonstrate throws’ keyword in java.","position":{"start":{"line":83,"column":5,"offset":3659},"end":{"line":83,"column":76,"offset":3730},"indent":[]}}],"position":{"start":{"line":83,"column":1,"offset":3655},"end":{"line":83,"column":76,"offset":3730},"indent":[]}},{"type":"code","lang":"js","meta":null,"value":"//Write a java program to demonstrate throws’ keyword in java.\npublic class FunyCodeException {\n    static void throwOne() throws IllegalAccessException\n      {\n        System.out.println(\"Inside throwOne\");\n        throw new IllegalAccessException(\"demo\");\n      }\n    public static void main(String args[])\n      {\n       try {\n         throwOne ();\n         }\n         catch (IllegalAccessException e)\n       {\n         System.out.println(\"Caught\" +e);\n        }\n      }\n    }","position":{"start":{"line":84,"column":1,"offset":3732},"end":{"line":103,"column":4,"offset":4240},"indent":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}},{"type":"code","lang":null,"meta":null,"value":"Output:\nInside throwOne\nCaughtjava.lang.IllegalAccessException: demo","position":{"start":{"line":104,"column":1,"offset":4242},"end":{"line":108,"column":4,"offset":4322},"indent":[1,1,1,1]}},{"type":"heading","depth":3,"children":[{"type":"text","value":"Example-4: Write a java program to demonstrate multiple exception in throws’ keyword in java.","position":{"start":{"line":109,"column":5,"offset":4328},"end":{"line":109,"column":98,"offset":4421},"indent":[]}}],"position":{"start":{"line":109,"column":1,"offset":4324},"end":{"line":109,"column":98,"offset":4421},"indent":[]}},{"type":"code","lang":"js","meta":null,"value":"//Write a java program to demonstrate multiple exception in throws’ keyword in java.\n  public class FunyCodeException {\n    static void throwOne(int a) throws NullPointerException, ArithmeticException\n        {\n        if (a==100)\n            throw new NullPointerException (\" Warning NullPointerException\");\n        else\n            throw new ArithmeticException (\" Warning ArithmeticException\");\n        }\n        public static void main(String args[])\n        {\n          try {\n               throwOne (100);\n               }\n           catch (Exception e)\n              {\n               System.out.println(\"Caught \" +e);\n              }\n             }\n           }","position":{"start":{"line":110,"column":1,"offset":4423},"end":{"line":131,"column":4,"offset":5122},"indent":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}},{"type":"code","lang":null,"meta":null,"value":"Output:\nCaught java.lang.NullPointerException:\nWarning NullPointerException","position":{"start":{"line":132,"column":1,"offset":5124},"end":{"line":136,"column":4,"offset":5211},"indent":[1,1,1,1]}},{"type":"heading","depth":2,"children":[{"type":"text","value":"Throw vs Throws in java","position":{"start":{"line":137,"column":4,"offset":5216},"end":{"line":137,"column":27,"offset":5239},"indent":[]}}],"position":{"start":{"line":137,"column":1,"offset":5213},"end":{"line":137,"column":27,"offset":5239},"indent":[]}},{"type":"list","ordered":false,"start":null,"spread":false,"children":[{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"Throws clause is used to declare an exception, which means it works similar to the try-catch block.","position":{"start":{"line":138,"column":3,"offset":5243},"end":{"line":138,"column":102,"offset":5342},"indent":[]}}],"position":{"start":{"line":138,"column":3,"offset":5243},"end":{"line":138,"column":102,"offset":5342},"indent":[]}}],"position":{"start":{"line":138,"column":1,"offset":5241},"end":{"line":138,"column":102,"offset":5342},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"On the other hand throw keyword is used to throw an exception explicitly.","position":{"start":{"line":139,"column":3,"offset":5346},"end":{"line":139,"column":76,"offset":5419},"indent":[]}}],"position":{"start":{"line":139,"column":3,"offset":5346},"end":{"line":139,"column":76,"offset":5419},"indent":[]}}],"position":{"start":{"line":139,"column":1,"offset":5344},"end":{"line":139,"column":76,"offset":5419},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"If we see syntax wise than throw is followed by an instance of Exception class and throws is followed by exception class names.","position":{"start":{"line":140,"column":3,"offset":5423},"end":{"line":140,"column":130,"offset":5550},"indent":[]}}],"position":{"start":{"line":140,"column":3,"offset":5423},"end":{"line":140,"column":130,"offset":5550},"indent":[]}}],"position":{"start":{"line":140,"column":1,"offset":5421},"end":{"line":140,"column":130,"offset":5550},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"For example: throw new ArithmeticException(“Arithmetic Exception”);","position":{"start":{"line":141,"column":3,"offset":5554},"end":{"line":141,"column":70,"offset":5621},"indent":[]}}],"position":{"start":{"line":141,"column":3,"offset":5554},"end":{"line":141,"column":70,"offset":5621},"indent":[]}}],"position":{"start":{"line":141,"column":1,"offset":5552},"end":{"line":141,"column":70,"offset":5621},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"Throw keyword is used in the method body to throw an exception, while throws is used in method signature to declare the exceptions that can occur in the statements present in the method.\n","position":{"start":{"line":142,"column":3,"offset":5625},"end":{"line":143,"column":1,"offset":5813},"indent":[1]}},{"type":"image","title":null,"url":"../../assets/javaPic/throw.png","alt":"Fig: Throwable in Java ","position":{"start":{"line":143,"column":1,"offset":5813},"end":{"line":143,"column":59,"offset":5871},"indent":[]}}],"position":{"start":{"line":142,"column":3,"offset":5625},"end":{"line":143,"column":59,"offset":5871},"indent":[1]}}],"position":{"start":{"line":142,"column":1,"offset":5623},"end":{"line":143,"column":59,"offset":5871},"indent":[1]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"All exception objects must belong to a subclass of the standard class java.lang.Throwable.","position":{"start":{"line":144,"column":3,"offset":5875},"end":{"line":144,"column":93,"offset":5965},"indent":[]}}],"position":{"start":{"line":144,"column":3,"offset":5875},"end":{"line":144,"column":93,"offset":5965},"indent":[]}}],"position":{"start":{"line":144,"column":1,"offset":5873},"end":{"line":144,"column":93,"offset":5965},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"In general, each different type of exception is represented by its own subclass of Throwable, and these subclasses are arranged in a fairly complex class hierarchy that shows the relationship among various types of exception.","position":{"start":{"line":145,"column":3,"offset":5969},"end":{"line":145,"column":228,"offset":6194},"indent":[]}}],"position":{"start":{"line":145,"column":3,"offset":5969},"end":{"line":145,"column":228,"offset":6194},"indent":[]}}],"position":{"start":{"line":145,"column":1,"offset":5967},"end":{"line":145,"column":228,"offset":6194},"indent":[]}}],"position":{"start":{"line":138,"column":1,"offset":5241},"end":{"line":145,"column":228,"offset":6194},"indent":[1,1,1,1,1,1,1]}},{"type":"heading","depth":2,"children":[{"type":"text","value":"Throwable","position":{"start":{"line":146,"column":4,"offset":6199},"end":{"line":146,"column":13,"offset":6208},"indent":[]}}],"position":{"start":{"line":146,"column":1,"offset":6196},"end":{"line":146,"column":13,"offset":6208},"indent":[]}},{"type":"list","ordered":false,"start":null,"spread":false,"children":[{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"Throwable has two direct subclasses, Error and Exception.","position":{"start":{"line":147,"column":3,"offset":6212},"end":{"line":147,"column":60,"offset":6269},"indent":[]}}],"position":{"start":{"line":147,"column":3,"offset":6212},"end":{"line":147,"column":60,"offset":6269},"indent":[]}}],"position":{"start":{"line":147,"column":1,"offset":6210},"end":{"line":147,"column":60,"offset":6269},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"These two subclasses in turn have many other predefined subclasses.","position":{"start":{"line":148,"column":3,"offset":6273},"end":{"line":148,"column":70,"offset":6340},"indent":[]}}],"position":{"start":{"line":148,"column":3,"offset":6273},"end":{"line":148,"column":70,"offset":6340},"indent":[]}}],"position":{"start":{"line":148,"column":1,"offset":6271},"end":{"line":148,"column":70,"offset":6340},"indent":[]}},{"type":"listItem","spread":false,"checked":null,"children":[{"type":"paragraph","children":[{"type":"text","value":"In addition, a programmer can create new exception classes to represent new types of exception.","position":{"start":{"line":149,"column":3,"offset":6344},"end":{"line":149,"column":98,"offset":6439},"indent":[]}}],"position":{"start":{"line":149,"column":3,"offset":6344},"end":{"line":149,"column":98,"offset":6439},"indent":[]}}],"position":{"start":{"line":149,"column":1,"offset":6342},"end":{"line":149,"column":98,"offset":6439},"indent":[]}}],"position":{"start":{"line":147,"column":1,"offset":6210},"end":{"line":149,"column":98,"offset":6439},"indent":[1,1]}},{"type":"export","value":"export const _frontmatter = {\"title\":\"Throw, Throws and Throwable in Java\",\"category\":\"Java\",\"author\":\"Anonymous\",\"tags\":[\"#java\",\"#tutorial\"],\"date\":\"2021-01-02T00:00:00.000Z\",\"thumbnailText\":\"Java Tutorial-30\"}","position":{"start":{"line":151,"column":1,"offset":6441},"end":{"line":151,"column":213,"offset":6653},"indent":[]}}],"position":{"start":{"line":1,"column":1,"offset":0},"end":{"line":151,"column":213,"offset":6653}}},"scopeImports":["import * as React from 'react'"],"scopeIdentifiers":["React"],"body":"var _excluded = [\"components\"];\n\nfunction _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }\n\nfunction _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }\n\nfunction _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }\n\n/* @jsxRuntime classic */\n\n/* @jsx mdx */\nvar _frontmatter = {\n  \"title\": \"Throw, Throws and Throwable in Java\",\n  \"category\": \"Java\",\n  \"author\": \"Anonymous\",\n  \"tags\": [\"#java\", \"#tutorial\"],\n  \"date\": \"2021-01-02T00:00:00.000Z\",\n  \"thumbnailText\": \"Java Tutorial-30\"\n};\nvar layoutProps = {\n  _frontmatter: _frontmatter\n};\nvar MDXLayout = \"wrapper\";\nreturn function MDXContent(_ref) {\n  var components = _ref.components,\n      props = _objectWithoutProperties(_ref, _excluded);\n\n  return mdx(MDXLayout, _extends({}, layoutProps, props, {\n    components: components,\n    mdxType: \"MDXLayout\"\n  }), mdx(\"h2\", {\n    \"id\": \"throw-throws-and-throwable-in-java\"\n  }, \"Throw, Throws and Throwable in Java\"), mdx(\"p\", null, \"The \\u201Cthrow\\u201D keyword is used to throw an exception. We can define our own set of conditions or rules and throw an exception explicitly using throw keyword. It is possible for your program to throw an exception explicitly, using the throw statement. The general form of throw is shown here:\"), mdx(\"h2\", {\n    \"id\": \"throw-throwableinstance\"\n  }, \"throw Throwableinstance;\"), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Throwableinstance must be an object of type Throwable or a subclass of Throwable.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Simple types, such as int or char, as well as non-Throwable classes, such as String and Object, cannot be used as exceptions.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"There are two ways you can obtain a Throwable object: using a parameter into a catch clause, or creating one with the new operator.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"The flow of execution stops immediately after the throw statement; any subsequent statements are not executed.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"The nearest enclosing try block is inspected to see if it has a catch statement that matches the type of the exception.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"If it does find a match, control is transferred to that statement. If not, then the next enclosing try statement is inspected, and so on.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"If no matching catch is found, then the default exception handler halts the program and prints the stack trace.\")), mdx(\"h3\", {\n    \"id\": \"example-1-write-a-java-program-to-implement-throw-keyword-in-java\"\n  }, \"Example-1: Write a java program to implement throw keyword in java.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-js\"\n  }, \"//Write a java program to implement throw keyword in java.\\n  public class FunyCodeException {\\n    static void throwDemo()\\n      {\\n       try\\n      {\\n       throw new NullPointerException(\\\"demo\\\");\\n      }\\n     catch(NullPointerException e)\\n     {\\n        System.out.println(\\\"Caught inside throwDemo.\\\");\\n        throw e; // rethrow the exception\\n      }\\n    }\\n    public static void main(String args[])\\n      {\\n       try\\n      {\\n       throwDemo();\\n      }\\n      catch(NullPointerException e)\\n      {\\n        System. out .println (\\\"Recaught Exception\\\");\\n       }\\n      }\\n     }\\n\")), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\"\n  }, \"Output:\\nCaught inside throwDemo.\\nRecaught Exception\\n\")), mdx(\"h3\", {\n    \"id\": \"example-2-write-a-java-program-to-check-weather-eligible-or-not-in-voting-registration-using-throw-keyword-in-java\"\n  }, \"Example-2: Write a java program to check weather eligible or not in voting registration using throw keyword in java.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-js\"\n  }, \"//Write a java program to check weather eligible or not in voting registration using throw keyword in java.\\n  public class FunyCodeException {\\n    static void ageCheck(int age) {\\n      if (age<18)\\n        throw new ArithmeticException(\\\"Not Elligible for Voting\\\");\\n      else\\n        System.out.println(\\\"Welcome, Elligible for Voting\\\");\\n      }\\n    public static void main(String args[]) {\\n       ageCheck(10);\\n      }\\n    }\\n\")), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\"\n  }, \"Output:\\nException in thread \\\"main\\\" java.lang.ArithmeticException: Not Elligible for Voting\\nat FunyCodeException.ageCheck(FunyCodeException.java:5)\\nat FunyCodeException.main(FunyCodeException.java:10)\\n\")), mdx(\"h2\", {\n    \"id\": \"throws-in-java\"\n  }, \"Throws in Java\"), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Throws keyword is used for handling checked exceptions . By using throws we can declare multiple exceptions in one go.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"If a method is capable of causing an exception that it does not handled, it must specify the behavior so that callers of the method can guard themselves against that exception.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"You do this by including a throws clause in the method\\u2019s declaration.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"A throws clause lists the types of exceptions that a method might throw.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"This is necessary for all exceptions, except those of type Error or RuntimeException, or any of their subclasses.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"All other exceptions that a method can throw must be declared in the throws clause.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"If they are not, a compile-time error will result.\")), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\"\n  }, \"Syntax:\\ntype method-name(parameter-list) throws exception-list\\n{\\n// body of method\\n}\\n\")), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Exception-list is a comma-separated list of the exceptions that a method can throw.\")), mdx(\"h3\", {\n    \"id\": \"example-3-write-a-java-program-to-demonstrate-throws-keyword-in-java\"\n  }, \"Example-3: Write a java program to demonstrate throws\\u2019 keyword in java.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-js\"\n  }, \"//Write a java program to demonstrate throws\\u2019 keyword in java.\\npublic class FunyCodeException {\\n    static void throwOne() throws IllegalAccessException\\n      {\\n        System.out.println(\\\"Inside throwOne\\\");\\n        throw new IllegalAccessException(\\\"demo\\\");\\n      }\\n    public static void main(String args[])\\n      {\\n       try {\\n         throwOne ();\\n         }\\n         catch (IllegalAccessException e)\\n       {\\n         System.out.println(\\\"Caught\\\" +e);\\n        }\\n      }\\n    }\\n\")), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\"\n  }, \"Output:\\nInside throwOne\\nCaughtjava.lang.IllegalAccessException: demo\\n\")), mdx(\"h3\", {\n    \"id\": \"example-4-write-a-java-program-to-demonstrate-multiple-exception-in-throws-keyword-in-java\"\n  }, \"Example-4: Write a java program to demonstrate multiple exception in throws\\u2019 keyword in java.\"), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\",\n    \"className\": \"language-js\"\n  }, \"//Write a java program to demonstrate multiple exception in throws\\u2019 keyword in java.\\n  public class FunyCodeException {\\n    static void throwOne(int a) throws NullPointerException, ArithmeticException\\n        {\\n        if (a==100)\\n            throw new NullPointerException (\\\" Warning NullPointerException\\\");\\n        else\\n            throw new ArithmeticException (\\\" Warning ArithmeticException\\\");\\n        }\\n        public static void main(String args[])\\n        {\\n          try {\\n               throwOne (100);\\n               }\\n           catch (Exception e)\\n              {\\n               System.out.println(\\\"Caught \\\" +e);\\n              }\\n             }\\n           }\\n\")), mdx(\"pre\", null, mdx(\"code\", {\n    parentName: \"pre\"\n  }, \"Output:\\nCaught java.lang.NullPointerException:\\nWarning NullPointerException\\n\")), mdx(\"h2\", {\n    \"id\": \"throw-vs-throws-in-java\"\n  }, \"Throw vs Throws in java\"), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Throws clause is used to declare an exception, which means it works similar to the try-catch block.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"On the other hand throw keyword is used to throw an exception explicitly.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"If we see syntax wise than throw is followed by an instance of Exception class and throws is followed by exception class names.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"For example: throw new ArithmeticException(\\u201CArithmetic Exception\\u201D);\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Throw keyword is used in the method body to throw an exception, while throws is used in method signature to declare the exceptions that can occur in the statements present in the method.\\n\", mdx(\"figure\", {\n    parentName: \"li\",\n    \"className\": \"gatsby-resp-image-figure\",\n    \"style\": {}\n  }, \"\\n    \", mdx(\"span\", {\n    parentName: \"figure\",\n    \"className\": \"gatsby-resp-image-wrapper\",\n    \"style\": {\n      \"position\": \"relative\",\n      \"display\": \"block\",\n      \"marginLeft\": \"auto\",\n      \"marginRight\": \"auto\",\n      \"maxWidth\": \"1010px\"\n    }\n  }, \"\\n      \", mdx(\"span\", {\n    parentName: \"span\",\n    \"className\": \"gatsby-resp-image-background-image\",\n    \"style\": {\n      \"paddingBottom\": \"60.35087719298245%\",\n      \"position\": \"relative\",\n      \"bottom\": \"0\",\n      \"left\": \"0\",\n      \"backgroundImage\": \"url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAMCAYAAABiDJ37AAAACXBIWXMAABJ0AAASdAHeZh94AAAB0klEQVQoz22T63LiMAyFef8H4lcfoPtjZ2cLuRS2lKYJAeceO7Fz/XYIUKBFMxopsnVyZB/PxnHkaMd4cRgxukVJM3nf91Pta8+pgUvvrc0uYN8tDAoWfwTWi6Cqmru1+5+f+8/57LZYKY04KMReomTDZZ/KFelHSBUlNFX1A/QW4w5Q1w3BZ0GR14zjMNW7AWplEPY/koVNHccPJxpvGV4+sqRCHCRhINm+ZexDiYwzyiBEHQSl76N2O+QuJN9sKN/fkbvdlfUw3ANGQrJZp7jLhJUdkyQVbZkjtx+Umw3S81B+QJ2myCCgcF/JVmvaWv+8lNsxuu6UGz3QtNexjJRIP6D0Pin9gK7rUEKQv70hfX9ifga8nkFdd7TtMMnk6F3bU6uWthkwWUq53aK8LaXn0dT1BFQeJzj77PsBG92domlxlzHW36NH/P51YPmS4Ng5tlUQ7jWPbGK4DwqchWDlxDhLwdqJcC1BGlc0ZsDonsb06LpD1y1FXmF0Mwm+bRqM1lM+yWYas2ooc02Ra9JYTa+jLDRd1z+Qx4DnbXFdB9u2WSwWWJaFlPLK8BCWOMuIlR1Nce3GvNoRlTIPX8YwDDw/PzOfz3l6eiLLsi9h/wfACpyw+5RMaAAAAABJRU5ErkJggg==')\",\n      \"backgroundSize\": \"cover\",\n      \"display\": \"block\"\n    }\n  }), \"\\n  \", mdx(\"img\", {\n    parentName: \"span\",\n    \"className\": \"gatsby-resp-image-image\",\n    \"alt\": \"Fig: Throwable in Java \",\n    \"title\": \"Fig: Throwable in Java \",\n    \"src\": \"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/96101/throw.png\",\n    \"srcSet\": [\"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/050f2/throw.png 285w\", \"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/2b0be/throw.png 570w\", \"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/96101/throw.png 1010w\"],\n    \"sizes\": \"(max-width: 1010px) 100vw, 1010px\",\n    \"style\": {\n      \"width\": \"100%\",\n      \"height\": \"100%\",\n      \"margin\": \"0\",\n      \"verticalAlign\": \"middle\",\n      \"position\": \"absolute\",\n      \"top\": \"0\",\n      \"left\": \"0\"\n    },\n    \"loading\": \"lazy\",\n    \"decoding\": \"async\"\n  }), \"\\n    \"), \"\\n    \", mdx(\"figcaption\", {\n    parentName: \"figure\",\n    \"className\": \"gatsby-resp-image-figcaption\"\n  }, \"Fig: Throwable in Java \"), \"\\n  \")), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"All exception objects must belong to a subclass of the standard class java.lang.Throwable.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"In general, each different type of exception is represented by its own subclass of Throwable, and these subclasses are arranged in a fairly complex class hierarchy that shows the relationship among various types of exception.\")), mdx(\"h2\", {\n    \"id\": \"throwable\"\n  }, \"Throwable\"), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Throwable has two direct subclasses, Error and Exception.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"These two subclasses in turn have many other predefined subclasses.\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"In addition, a programmer can create new exception classes to represent new types of exception.\")));\n}\n;\nMDXContent.isMDXComponent = true;","rawMDXOutput":"/* @jsx mdx */\nimport { mdx } from '@mdx-js/react';\n/* @jsxRuntime classic */\n/* @jsx mdx */\n\nexport const _frontmatter = {\n  \"title\": \"Throw, Throws and Throwable in Java\",\n  \"category\": \"Java\",\n  \"author\": \"Anonymous\",\n  \"tags\": [\"#java\", \"#tutorial\"],\n  \"date\": \"2021-01-02T00:00:00.000Z\",\n  \"thumbnailText\": \"Java Tutorial-30\"\n};\n\nconst layoutProps = {\n  _frontmatter\n};\nconst MDXLayout = \"wrapper\"\nexport default function MDXContent({\n  components,\n  ...props\n}) {\n  return <MDXLayout {...layoutProps} {...props} components={components} mdxType=\"MDXLayout\">\n    <h2 {...{\n      \"id\": \"throw-throws-and-throwable-in-java\"\n    }}>{`Throw, Throws and Throwable in Java`}</h2>\n    <p>{`The “throw” keyword is used to throw an exception. We can define our own set of conditions or rules and throw an exception explicitly using throw keyword. It is possible for your program to throw an exception explicitly, using the throw statement. The general form of throw is shown here:`}</p>\n    <h2 {...{\n      \"id\": \"throw-throwableinstance\"\n    }}>{`throw Throwableinstance;`}</h2>\n    <ul>\n      <li parentName=\"ul\">{`Throwableinstance must be an object of type Throwable or a subclass of Throwable.`}</li>\n      <li parentName=\"ul\">{`Simple types, such as int or char, as well as non-Throwable classes, such as String and Object, cannot be used as exceptions.`}</li>\n      <li parentName=\"ul\">{`There are two ways you can obtain a Throwable object: using a parameter into a catch clause, or creating one with the new operator.`}</li>\n      <li parentName=\"ul\">{`The flow of execution stops immediately after the throw statement; any subsequent statements are not executed.`}</li>\n      <li parentName=\"ul\">{`The nearest enclosing try block is inspected to see if it has a catch statement that matches the type of the exception.`}</li>\n      <li parentName=\"ul\">{`If it does find a match, control is transferred to that statement. If not, then the next enclosing try statement is inspected, and so on.`}</li>\n      <li parentName=\"ul\">{`If no matching catch is found, then the default exception handler halts the program and prints the stack trace.`}</li>\n    </ul>\n    <h3 {...{\n      \"id\": \"example-1-write-a-java-program-to-implement-throw-keyword-in-java\"\n    }}>{`Example-1: Write a java program to implement throw keyword in java.`}</h3>\n    <pre><code parentName=\"pre\" {...{\n        \"className\": \"language-js\"\n      }}>{`//Write a java program to implement throw keyword in java.\n  public class FunyCodeException {\n    static void throwDemo()\n      {\n       try\n      {\n       throw new NullPointerException(\"demo\");\n      }\n     catch(NullPointerException e)\n     {\n        System.out.println(\"Caught inside throwDemo.\");\n        throw e; // rethrow the exception\n      }\n    }\n    public static void main(String args[])\n      {\n       try\n      {\n       throwDemo();\n      }\n      catch(NullPointerException e)\n      {\n        System. out .println (\"Recaught Exception\");\n       }\n      }\n     }\n`}</code></pre>\n    <pre><code parentName=\"pre\" {...{}}>{`Output:\nCaught inside throwDemo.\nRecaught Exception\n`}</code></pre>\n    <h3 {...{\n      \"id\": \"example-2-write-a-java-program-to-check-weather-eligible-or-not-in-voting-registration-using-throw-keyword-in-java\"\n    }}>{`Example-2: Write a java program to check weather eligible or not in voting registration using throw keyword in java.`}</h3>\n    <pre><code parentName=\"pre\" {...{\n        \"className\": \"language-js\"\n      }}>{`//Write a java program to check weather eligible or not in voting registration using throw keyword in java.\n  public class FunyCodeException {\n    static void ageCheck(int age) {\n      if (age<18)\n        throw new ArithmeticException(\"Not Elligible for Voting\");\n      else\n        System.out.println(\"Welcome, Elligible for Voting\");\n      }\n    public static void main(String args[]) {\n       ageCheck(10);\n      }\n    }\n`}</code></pre>\n    <pre><code parentName=\"pre\" {...{}}>{`Output:\nException in thread \"main\" java.lang.ArithmeticException: Not Elligible for Voting\nat FunyCodeException.ageCheck(FunyCodeException.java:5)\nat FunyCodeException.main(FunyCodeException.java:10)\n`}</code></pre>\n    <h2 {...{\n      \"id\": \"throws-in-java\"\n    }}>{`Throws in Java`}</h2>\n    <ul>\n      <li parentName=\"ul\">{`Throws keyword is used for handling checked exceptions . By using throws we can declare multiple exceptions in one go.`}</li>\n      <li parentName=\"ul\">{`If a method is capable of causing an exception that it does not handled, it must specify the behavior so that callers of the method can guard themselves against that exception.`}</li>\n      <li parentName=\"ul\">{`You do this by including a throws clause in the method’s declaration.`}</li>\n      <li parentName=\"ul\">{`A throws clause lists the types of exceptions that a method might throw.`}</li>\n      <li parentName=\"ul\">{`This is necessary for all exceptions, except those of type Error or RuntimeException, or any of their subclasses.`}</li>\n      <li parentName=\"ul\">{`All other exceptions that a method can throw must be declared in the throws clause.`}</li>\n      <li parentName=\"ul\">{`If they are not, a compile-time error will result.`}</li>\n    </ul>\n    <pre><code parentName=\"pre\" {...{}}>{`Syntax:\ntype method-name(parameter-list) throws exception-list\n{\n// body of method\n}\n`}</code></pre>\n    <ul>\n      <li parentName=\"ul\">{`Exception-list is a comma-separated list of the exceptions that a method can throw.`}</li>\n    </ul>\n    <h3 {...{\n      \"id\": \"example-3-write-a-java-program-to-demonstrate-throws-keyword-in-java\"\n    }}>{`Example-3: Write a java program to demonstrate throws’ keyword in java.`}</h3>\n    <pre><code parentName=\"pre\" {...{\n        \"className\": \"language-js\"\n      }}>{`//Write a java program to demonstrate throws’ keyword in java.\npublic class FunyCodeException {\n    static void throwOne() throws IllegalAccessException\n      {\n        System.out.println(\"Inside throwOne\");\n        throw new IllegalAccessException(\"demo\");\n      }\n    public static void main(String args[])\n      {\n       try {\n         throwOne ();\n         }\n         catch (IllegalAccessException e)\n       {\n         System.out.println(\"Caught\" +e);\n        }\n      }\n    }\n`}</code></pre>\n    <pre><code parentName=\"pre\" {...{}}>{`Output:\nInside throwOne\nCaughtjava.lang.IllegalAccessException: demo\n`}</code></pre>\n    <h3 {...{\n      \"id\": \"example-4-write-a-java-program-to-demonstrate-multiple-exception-in-throws-keyword-in-java\"\n    }}>{`Example-4: Write a java program to demonstrate multiple exception in throws’ keyword in java.`}</h3>\n    <pre><code parentName=\"pre\" {...{\n        \"className\": \"language-js\"\n      }}>{`//Write a java program to demonstrate multiple exception in throws’ keyword in java.\n  public class FunyCodeException {\n    static void throwOne(int a) throws NullPointerException, ArithmeticException\n        {\n        if (a==100)\n            throw new NullPointerException (\" Warning NullPointerException\");\n        else\n            throw new ArithmeticException (\" Warning ArithmeticException\");\n        }\n        public static void main(String args[])\n        {\n          try {\n               throwOne (100);\n               }\n           catch (Exception e)\n              {\n               System.out.println(\"Caught \" +e);\n              }\n             }\n           }\n`}</code></pre>\n    <pre><code parentName=\"pre\" {...{}}>{`Output:\nCaught java.lang.NullPointerException:\nWarning NullPointerException\n`}</code></pre>\n    <h2 {...{\n      \"id\": \"throw-vs-throws-in-java\"\n    }}>{`Throw vs Throws in java`}</h2>\n    <ul>\n      <li parentName=\"ul\">{`Throws clause is used to declare an exception, which means it works similar to the try-catch block.`}</li>\n      <li parentName=\"ul\">{`On the other hand throw keyword is used to throw an exception explicitly.`}</li>\n      <li parentName=\"ul\">{`If we see syntax wise than throw is followed by an instance of Exception class and throws is followed by exception class names.`}</li>\n      <li parentName=\"ul\">{`For example: throw new ArithmeticException(“Arithmetic Exception”);`}</li>\n      <li parentName=\"ul\">{`Throw keyword is used in the method body to throw an exception, while throws is used in method signature to declare the exceptions that can occur in the statements present in the method.\n`}<figure parentName=\"li\" {...{\n          \"className\": \"gatsby-resp-image-figure\",\n          \"style\": {}\n        }}>{`\n    `}<span parentName=\"figure\" {...{\n            \"className\": \"gatsby-resp-image-wrapper\",\n            \"style\": {\n              \"position\": \"relative\",\n              \"display\": \"block\",\n              \"marginLeft\": \"auto\",\n              \"marginRight\": \"auto\",\n              \"maxWidth\": \"1010px\"\n            }\n          }}>{`\n      `}<span parentName=\"span\" {...{\n              \"className\": \"gatsby-resp-image-background-image\",\n              \"style\": {\n                \"paddingBottom\": \"60.35087719298245%\",\n                \"position\": \"relative\",\n                \"bottom\": \"0\",\n                \"left\": \"0\",\n                \"backgroundImage\": \"url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAMCAYAAABiDJ37AAAACXBIWXMAABJ0AAASdAHeZh94AAAB0klEQVQoz22T63LiMAyFef8H4lcfoPtjZ2cLuRS2lKYJAeceO7Fz/XYIUKBFMxopsnVyZB/PxnHkaMd4cRgxukVJM3nf91Pta8+pgUvvrc0uYN8tDAoWfwTWi6Cqmru1+5+f+8/57LZYKY04KMReomTDZZ/KFelHSBUlNFX1A/QW4w5Q1w3BZ0GR14zjMNW7AWplEPY/koVNHccPJxpvGV4+sqRCHCRhINm+ZexDiYwzyiBEHQSl76N2O+QuJN9sKN/fkbvdlfUw3ANGQrJZp7jLhJUdkyQVbZkjtx+Umw3S81B+QJ2myCCgcF/JVmvaWv+8lNsxuu6UGz3QtNexjJRIP6D0Pin9gK7rUEKQv70hfX9ifga8nkFdd7TtMMnk6F3bU6uWthkwWUq53aK8LaXn0dT1BFQeJzj77PsBG92domlxlzHW36NH/P51YPmS4Ng5tlUQ7jWPbGK4DwqchWDlxDhLwdqJcC1BGlc0ZsDonsb06LpD1y1FXmF0Mwm+bRqM1lM+yWYas2ooc02Ra9JYTa+jLDRd1z+Qx4DnbXFdB9u2WSwWWJaFlPLK8BCWOMuIlR1Nce3GvNoRlTIPX8YwDDw/PzOfz3l6eiLLsi9h/wfACpyw+5RMaAAAAABJRU5ErkJggg==')\",\n                \"backgroundSize\": \"cover\",\n                \"display\": \"block\"\n              }\n            }}></span>{`\n  `}<img parentName=\"span\" {...{\n              \"className\": \"gatsby-resp-image-image\",\n              \"alt\": \"Fig: Throwable in Java \",\n              \"title\": \"Fig: Throwable in Java \",\n              \"src\": \"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/96101/throw.png\",\n              \"srcSet\": [\"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/050f2/throw.png 285w\", \"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/2b0be/throw.png 570w\", \"/funycode/static/09b43b074d53a4a68a69c8d7ff48fd17/96101/throw.png 1010w\"],\n              \"sizes\": \"(max-width: 1010px) 100vw, 1010px\",\n              \"style\": {\n                \"width\": \"100%\",\n                \"height\": \"100%\",\n                \"margin\": \"0\",\n                \"verticalAlign\": \"middle\",\n                \"position\": \"absolute\",\n                \"top\": \"0\",\n                \"left\": \"0\"\n              },\n              \"loading\": \"lazy\",\n              \"decoding\": \"async\"\n            }}></img>{`\n    `}</span>{`\n    `}<figcaption parentName=\"figure\" {...{\n            \"className\": \"gatsby-resp-image-figcaption\"\n          }}>{`Fig: Throwable in Java `}</figcaption>{`\n  `}</figure></li>\n      <li parentName=\"ul\">{`All exception objects must belong to a subclass of the standard class java.lang.Throwable.`}</li>\n      <li parentName=\"ul\">{`In general, each different type of exception is represented by its own subclass of Throwable, and these subclasses are arranged in a fairly complex class hierarchy that shows the relationship among various types of exception.`}</li>\n    </ul>\n    <h2 {...{\n      \"id\": \"throwable\"\n    }}>{`Throwable`}</h2>\n    <ul>\n      <li parentName=\"ul\">{`Throwable has two direct subclasses, Error and Exception.`}</li>\n      <li parentName=\"ul\">{`These two subclasses in turn have many other predefined subclasses.`}</li>\n      <li parentName=\"ul\">{`In addition, a programmer can create new exception classes to represent new types of exception.`}</li>\n    </ul>\n\n    </MDXLayout>;\n}\n\n;\nMDXContent.isMDXComponent = true;"}}